fix: unwrap, panicked at src/units/rib_unit/rib.rs:1065:65
When we create SearchResult, during generation of json we use live ingress id,
so it might happen, when we reach route, ingressid doesnt exist anymore.
Make snapshot of ingress with SearchResult.